### ISSUE TITLE
[Errno 22] Invalid argument , path reading problems

### ISSUE THREAD

**Issue by MrKuenning** [siddharthlh24/ViewSDimageInNewTab#1]
I have tried to get this to work multiple times on both prod and dev installs of A1111.

I am able to create the temp image manually and see it in the HTML page, but the webUI can not create the temp image.

I have the code in my images.py
![2024-03-21 10_43_44-E__AI_A1111-Portable Dev_webui_modules_images py - Notepad++](https://github.com/siddharthlh24/ViewSDimageInNewTab/assets/16549268/babf1cd2-ff03-40b8-848c-6106da37dc7c)

but I get the following error in the consolel:

` OSError: [Errno 22] Invalid argument: 'E:\temp\\currimg.png'`

Full Message:

```
*** Error completing request████████████████████████████████▊    | 19/20 [00:02<00:00,  9.84it/s]

*** Arguments: ('task(1r81vzq2xr57es4)', <gradio.routes.Request object at 0x000002CADC76DFF0>, '', '', [], 20, 'Euler a', 1, 1, 7, 704, 512, False, 0.35, 2, '4x Foolhardy Remacri', 15, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, -1, False, -1, 0, 0, 0, False, '', 0.8, UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=64, threshold_a=64, threshold_b=64, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=64, threshold_a=64, threshold_b=64, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=64, threshold_a=64, threshold_b=64, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), None, False, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CUDA', False, 0, 'None', '', None, False, False, 0.5, 0, True, False, False, False, 'base', False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "E:\AI\A1111-Portable Dev\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\AI\A1111-Portable Dev\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\AI\A1111-Portable Dev\webui\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "E:\AI\A1111-Portable Dev\webui\modules\processing.py", line 792, in process_images
        res = process_images_inner(p)
      File "E:\AI\A1111-Portable Dev\webui\extensions\2-Controlnet\scripts\batch_hijack.py", line 59, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\AI\A1111-Portable Dev\webui\modules\processing.py", line 1023, in process_images_inner
        images.save_image(image, p.outpath_samples, "", p.seeds[i], p.prompts[i], opts.samples_format, info=infotext(i), p=p)
      File "E:\AI\A1111-Portable Dev\webui\modules\images.py", line 615, in save_image
        image.save(file_path_temp)
      File "E:\AI\A1111-Portable Dev\system\python\lib\site-packages\PIL\Image.py", line 2429, in save
        fp = builtins.open(filename, "w+b")
    OSError: [Errno 22] Invalid argument: 'E:\temp\\currimg.png'

---
```

I don't know what the double backslash is from, as it is not typed that way in the python file.
I also don't get any generated images in my output folder.

I wonder if instead of modifying the image generation script to create a duplicate temp image, we just have the HTML file monitor the output folders and display whatever the newest generated image is.

**Comment by siddharthlh24** [comment]
i think python is acting up , try :: **path = r"E:\temp\currimg.png"** , that will cancel out any interpretations as extra characters etc.

**Comment by MrKuenning** [comment]
Thanks that fixed it.  I made a toggle button to scale image to fit window.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Image Display</title>
    <style>
        body {
            margin: 0;
            overflow: hidden; /* Remove any default margin and scrolling */
            background-color: black; /* Set background color to black */
            color: white; /* Set text color to white */
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 100vh;
            position: relative; /* Added to position the toggle button */
        }

        h1 {
            text-align: center;
        }

        img {
            max-width: 100%;
            max-height: calc(100vh - 40px); /* Adjusted to match window height */
            margin: auto;
        }

        #toggleButton {
            position: absolute;
            top: 10px;
            left: 10px; /* Left-aligned */
            background-color: white;
            color: black;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <button id="toggleButton" onclick="toggleFit()">Toggle Fit</button>
    <h1>Image Display</h1>
    <!-- Adjust path here accordingly -->
    <img id="currentImage" src="file:///E:/AI/Output/Temp/temp.jpg" alt="Current Image">

    <script>
        var fitToWindow = false;

        function refreshImage() {
            var imgElement = document.getElementById('currentImage');
            imgElement.src = imgElement.src.split('?')[0] + "?" + new Date().getTime(); // Add timestamp to force refresh
            if (fitToWindow) {
                var windowWidth = window.innerWidth;
                var windowHeight = window.innerHeight - 40; // Adjusted to match window height
                var imageAspectRatio = imgElement.naturalWidth / imgElement.naturalHeight;
                var windowAspectRatio = windowWidth / windowHeight;
                
                if (imageAspectRatio > windowAspectRatio) {
                    // Image is wider than the window
                    imgElement.style.width = '100%';
                    imgElement.style.height = 'auto';
                } else {
                    // Image is taller than or equal to the window
                    imgElement.style.width = 'auto';
                    imgElement.style.height = 'calc(100vh - 40px)'; // Adjusted to match window height
                }
            } else {
                imgElement.style.width = '';
                imgElement.style.height = '';
            }
        }

        // Refresh the image every 1 second (adjust as needed)
        setInterval(refreshImage, 1000);

        function toggleFit() {
            fitToWindow = !fitToWindow;
            refreshImage();
        }

        // Call refreshImage() when the window is resized
        window.addEventListener('resize', refreshImage);
    </script>
</body>
</html>

```
